### PR TITLE
Update readme and minor changes

### PR DESCRIPTION
**Pull request by sphinks**
I try to use this tap to get data from bigquery, but have to fix several issues, so doing backmerge PR.
1. Fix readme.
2. Add output of state message to be compatible with any target.
3. Fix lost require lib in setup script.

### CODE REVIEW

**Comment by daigotanaka** [comment]
@sphinks Thanks for improving the code and docs! Looking good.

**Comment by daigotanaka** [comment]
@sphinks Can you review this (breaking change v0.3.0)
https://github.com/anelendata/tap_bigquery/pull/3
I also wanted to discuss the release on PyPi since you did that with the previous version. Thx!

**Comment by sphinks** [comment]
@daigotanaka I'm not really good with Python, but I do not notice any issues. Also, I'm not sure I can be mentioned as author yet (just fix couple issues:)), I suppose contributor is much close to the truth :)

Do you want me to release it on PyPi?

**Comment by daigotanaka** [comment]
@sphinks got it about contributor. Can you add me (daigotanaka) as a collaborator at https://pypi.org/manage/project/tap-bigquery/collaboration so I don't have to contact you every time I need to release? Thx!

**Comment by sphinks** [comment]
@daigotanaka done, you can use it.

**Comment by sphinks** [comment]
It is make sense!

**Pull request merged**
